### ISSUE TITLE
Add `exceptions` instances

### ISSUE THREAD

**Issue by ocramz** [minad/writer-cps-transformers#4]
I found myself needing the MonadThrow and MonadCatch instances of the CPS version of WriterT , so I understand they should appear here, though this will introduce a new `exceptions` dependency.

What do you think?

**Comment by minad** [comment]
Until now I tried to keep the dependencies low since the package should just act as a small drop-in replacement for transformers and mtl. All instances are provided by orphan packages, e.g., [writer-cps-mtl](https://hackage.haskell.org/package/writer-cps-mtl), [writer-cps-mtl](https://hackage.haskell.org/package/writer-cps-lens), ... I think this is an acceptable use of orphan instances since those packages act as the canonical source.
 
writer-cps-mtl provides MonadError. About exceptions and MonadThrow, MonadCatch - what do you need those for? I am asking since I've not used them and exception masking yet.

**Comment by ocramz** [comment]
@minad I've started using `exceptions` following this advice https://www.fpcomplete.com/blog/2016/11/exceptions-best-practices-haskell , and seeing that it is slowly becoming standard. 

In my current project (https://github.com/ocramz/sparse-linear-algebra), I use transformers, mtl and writer-cps-transformers , and since I'd like it to become a foundation to other libraries, I wouldn't want to provide my own instances of MonadThrow etc. .

This brings us to a conundrum; where should those instances be?

**Comment by minad** [comment]
Ok. But I am still trying to understand why one would use MonadThrow/MonadCatch instead of MonadError...

My suggestion concerning the instances would be to put them in a separate package writer-cps-exceptions as orphans . Even writer-cps-mtl is a separate package only providing orphans.

What do you think?
