### ISSUE TITLE
Current state of this package is confusing

### ISSUE THREAD

**Issue by sjakobi** [minad/writer-cps-transformers#9]
I had to find https://github.com/minad/writer-cps-transformers/issues/7 to understand why there are no module listed at http://hackage.haskell.org/package/writer-cps-transformers-0.5.6.0.

Would you mind properly deprecating the package and directing people to `transformers`?

**Comment by quasicomputational** [comment]
I don't think it can be formally deprecated because pre-8.8 (or is it 8.6?) GHCs need a compatibility shim, and the `transformers-compat` plan is to keep this package providing those. Though, I think I only know this because I've been keeping half an eye on issue chatter, so it could probably do with being written down somewhere more prominently.

**Comment by minad** [comment]
Yes, it won't be deprecated. But the description should make clear why the newest package version is empty.
